// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nmf_als
Rcpp::List nmf_als(const Eigen::MatrixXd& X, const int low_dim, const Rcpp::Nullable<Eigen::MatrixXd> W_init, const Rcpp::Nullable<Eigen::MatrixXd> H_init, const double tol, const int max_iter, const bool parallel, const int ncores);
RcppExport SEXP _nnmf_nmf_als(SEXP XSEXP, SEXP low_dimSEXP, SEXP W_initSEXP, SEXP H_initSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP parallelSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type low_dim(low_dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Eigen::MatrixXd> >::type W_init(W_initSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Eigen::MatrixXd> >::type H_init(H_initSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< const int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(nmf_als(X, low_dim, W_init, H_init, tol, max_iter, parallel, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nnmf_nmf_als", (DL_FUNC) &_nnmf_nmf_als, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_nnmf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
