// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nmf_pred_cpp
Rcpp::List nmf_pred_cpp(const Eigen::MatrixXd& X, const Eigen::MatrixXd& H, const double ridge, const int ncores);
RcppExport SEXP _nnmf_nmf_pred_cpp(SEXP XSEXP, SEXP HSEXP, SEXP ridgeSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< const int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(nmf_pred_cpp(X, H, ridge, ncores));
    return rcpp_result_gen;
END_RCPP
}
// nmf_als_cpp
Rcpp::List nmf_als_cpp(const Eigen::MatrixXd& X, const int low_dim, const Rcpp::Nullable<Eigen::MatrixXd> H_init, const double lr_h, const double tol, const int max_iter, const double ridge, const int ncores);
RcppExport SEXP _nnmf_nmf_als_cpp(SEXP XSEXP, SEXP low_dimSEXP, SEXP H_initSEXP, SEXP lr_hSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP ridgeSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type low_dim(low_dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Eigen::MatrixXd> >::type H_init(H_initSEXP);
    Rcpp::traits::input_parameter< const double >::type lr_h(lr_hSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< const int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(nmf_als_cpp(X, low_dim, H_init, lr_h, tol, max_iter, ridge, ncores));
    return rcpp_result_gen;
END_RCPP
}
// nmf_reg_cpp
Rcpp::List nmf_reg_cpp(const Eigen::MatrixXd& X, const Eigen::MatrixXd& Z, const int low_dim, const Rcpp::Nullable<Eigen::MatrixXd> H_init, const int max_iter, const double tol, const int ncores);
RcppExport SEXP _nnmf_nmf_reg_cpp(SEXP XSEXP, SEXP ZSEXP, SEXP low_dimSEXP, SEXP H_initSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP ncoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int >::type low_dim(low_dimSEXP);
    Rcpp::traits::input_parameter< const Rcpp::Nullable<Eigen::MatrixXd> >::type H_init(H_initSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type ncores(ncoresSEXP);
    rcpp_result_gen = Rcpp::wrap(nmf_reg_cpp(X, Z, low_dim, H_init, max_iter, tol, ncores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nnmf_nmf_pred_cpp", (DL_FUNC) &_nnmf_nmf_pred_cpp, 4},
    {"_nnmf_nmf_als_cpp", (DL_FUNC) &_nnmf_nmf_als_cpp, 8},
    {"_nnmf_nmf_reg_cpp", (DL_FUNC) &_nnmf_nmf_reg_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_nnmf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
