# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nmf_pred_cpp <- function(X, H, ridge, ncores) {
    .Call(`_nnmf_nmf_pred_cpp`, X, H, ridge, ncores)
}

nmf_als_cpp <- function(X, low_dim, H_init, lr_h, tol, max_iter, ridge, ncores) {
    .Call(`_nnmf_nmf_als_cpp`, X, low_dim, H_init, lr_h, tol, max_iter, ridge, ncores)
}

nmf_reg_cpp <- function(X, Z, low_dim, H_init, max_iter, tol, ncores) {
    .Call(`_nnmf_nmf_reg_cpp`, X, Z, low_dim, H_init, max_iter, tol, ncores)
}

